title: Op wie kan ik stemmen?
description: >- # this means to ignore newlines until "baseurl:"
  Vind het antwoord op één simpele vraag: op wie kan ik stemmen bij de verkiezingen?
baseurl: ""
url: "https://opwiekanikstemmen.nl"
github_username: Opwiekanikstemmen-nl
themecolor: "#fee1c2"
keywords: "verkiezingen, tweedekamer, politiek, keuze, kieswijzer, advies, stemmen, kiezer"

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package-lock.json
  - package.json
  - src